from __future__ import annotations

import argparse
import json
from pathlib import Path

from occupational_fitness_rag.case_intake.batch import (
    prepare_case_directory,
    write_results_jsonl,
    write_workflow_artifacts,
)
from occupational_fitness_rag.case_intake.evaluation import exact_field_accuracy, load_jsonl
from occupational_fitness_rag.factory import build_chroma_pipeline
from occupational_fitness_rag.indexing.chroma_store import ChromaVectorStore
from occupational_fitness_rag.ingestion.pipeline import ingest_pdf_to_chunks, write_chunks_jsonl
from occupational_fitness_rag.schemas.rule_result import RuleResult
from occupational_fitness_rag.settings import load_settings


def cmd_ingest(args: argparse.Namespace) -> None:
    settings = load_settings(args.config)
    chunks = ingest_pdf_to_chunks(args.pdf, settings)
    processed = Path(args.processed)
    write_chunks_jsonl(chunks, processed)
    store = ChromaVectorStore(settings.index.persist_directory, settings.index.collection_name)
    store.add(chunks)
    classified = sum(1 for c in chunks if c.metadata.get("category") != "unclassified")
    print(
        json.dumps(
            {
                "chunks": len(chunks),
                "classified_chunks": classified,
                "unclassified_chunks": len(chunks) - classified,
                "processed_jsonl": str(processed),
                "collection": settings.index.collection_name,
            },
            indent=2,
        )
    )


def cmd_retrieve(args: argparse.Namespace) -> None:
    settings = load_settings(args.config)
    pipeline = build_chroma_pipeline(settings)
    payload = json.loads(Path(args.rule_result).read_text(encoding="utf-8"))
    result = RuleResult.model_validate(payload)
    pack = pipeline.run(result)
    text = pack.model_dump_json(indent=2)
    if args.output:
        Path(args.output).write_text(text, encoding="utf-8")
    print(text)


def cmd_prepare_cases(args: argparse.Namespace) -> None:
    results = prepare_case_directory(args.input_dir)
    write_results_jsonl(results, args.intake_output)
    write_workflow_artifacts(results, args.structured_output, args.condition_output)
    print(
        json.dumps(
            {
                "cases": len(results),
                "intake_output": args.intake_output,
                "structured_case_output": args.structured_output,
                "condition_map_output": args.condition_output,
                "guardrail": "No deterministic medical fitness outcome is generated by this command.",
            },
            indent=2,
        )
    )


def cmd_evaluate_extraction(args: argparse.Namespace) -> None:
    predictions = load_jsonl(args.predictions)
    gold = load_jsonl(args.gold)
    metrics = exact_field_accuracy(predictions, gold)
    print(json.dumps(metrics, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser(prog="fitness-rag")
    sub = parser.add_subparsers(dest="command", required=True)

    ingest = sub.add_parser("ingest", help="Parse, annotate and index an Austroads PDF")
    ingest.add_argument("--pdf", required=True)
    ingest.add_argument("--config", default="configs/rag.yaml")
    ingest.add_argument("--processed", default="data/processed/austroads_chunks.jsonl")
    ingest.set_defaults(func=cmd_ingest)

    retrieve = sub.add_parser("retrieve", help="Retrieve guideline evidence from rule_result.json")
    retrieve.add_argument("--rule-result", required=True)
    retrieve.add_argument("--config", default="configs/rag.yaml")
    retrieve.add_argument("--output")
    retrieve.set_defaults(func=cmd_retrieve)

    prepare = sub.add_parser(
        "prepare-cases",
        help="Parse the supplied SYN-M2 nurse-note fixtures and emit workflow artifacts",
    )
    prepare.add_argument("--input-dir", default="data/cases/nurse_notes")
    prepare.add_argument("--intake-output", default="data/cases/processed/intake_results.jsonl")
    prepare.add_argument(
        "--structured-output", default="data/cases/processed/structured_cases.jsonl"
    )
    prepare.add_argument("--condition-output", default="data/cases/processed/condition_maps.jsonl")
    prepare.set_defaults(func=cmd_prepare_cases)

    evaluate = sub.add_parser(
        "evaluate-extraction",
        help="Measure field-level extraction accuracy against the supplied fixture gold set",
    )
    evaluate.add_argument("--predictions", default="data/cases/processed/intake_results.jsonl")
    evaluate.add_argument("--gold", default="data/cases/gold/structured_cases.jsonl")
    evaluate.set_defaults(func=cmd_evaluate_extraction)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
